global:
  scrape_interval: 15s  # Intervalo para coletar métricas

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask1:5000', 'flask2:5000', 'flask3:5000']  # Alvo de scrape para os containers
